# This file was generated by GoReleaser. DO NOT EDIT.
cask "supercool" do
  version "1.0.0-rc.1"

  on_macos do
    on_arm do
      sha256 "c6111d571ca08857fd623aece813441b060b4baeeb101699d9281018df701ea2"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1e5445cae5d4b06923fc0d000b3697fc0fc45a5ad857a76a95db74895a7c89a3"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5b70f4513b4056910657a5c0a9d774a103881214c43133ab9dcf661a872552de"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d495761c706be7474c9f0f0ac2dbe022c8759c5a8a1364674d3b27bc1d1f7471"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_linux_amd64.tar.gz"
    end
  end

  name "supercool"
  desc "Your SuperCool agent in the terminal"
  homepage "https://supercool.com/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "supercool"

  # No zap stanza required
end
