# This file was generated by GoReleaser. DO NOT EDIT.
cask "supercool" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "5776f402f7bb9dc5ed5615055926f78610c307def3c80a5ebe7574d53762eacd"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4513ff8460e7b4734bd8bff12c329c9b2d950101083772e65d57084be4927f29"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "26ff78a5f77613c28fab3b443fa4665b43e66fb1de4c73a96144d9ffb82ff9f9"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77d140090ed55232c7dccd799b803d16a3647aab816b9404ef91f2190163820c"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_linux_amd64.tar.gz"
    end
  end

  name "supercool"
  desc "Your SuperCool agent in the terminal"
  homepage "https://supercool.com/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "supercool"

  # No zap stanza required
end
