# This file was generated by GoReleaser. DO NOT EDIT.
cask "supercool" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "e1acdca919c0d0cd6b47415fd3191e01a4bd0a0bcf6a169bf6a1c11836071997"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "db0d2506ed242e968e2b93cf7c43272194cabc5c32554cc3bced30df6dcaee29"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8639ce9dd0c8c77959ff7634082d62aae81c78e13dd5d7602771d639f3e1489d"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b4a984329dd0ce78829fddce93a200739cf85491a5b2400d3b123e815636888"
      url "https://github.com/Famous-Labs/supercool-cli/releases/download/v#{version}/supercool_#{version}_linux_amd64.tar.gz"
    end
  end

  name "supercool"
  desc "Your SuperCool agent in the terminal"
  homepage "https://supercool.com/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "supercool"

  # No zap stanza required
end
